backend:
  name: github
  repo: sukhavacancy/sukhavacancy.github.io
  branch: main
  auth_type: token  # यह लाइन गिटहब को बताएगी कि हम टोकन इस्तेमाल कर रहे हैं

media_folder: "assets/images"
public_folder: "/assets/images"

collections:
  - name: "posts"
    label: "Posts"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Categories", name: "categories", widget: "string", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
